version: '3'
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: weatherbot
    networks:
      kitler:
        aliases:
          - wetbot
  elastic:
    image: "docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.0"
    container_name: elasticsearch
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - ES_JAVA_OPTS=-XX:-UseGCTaskAffinity -XX:-BindGCTaskThreadsToCPUs -XX:ParallelGCThreads=1 -XX:ParallelCMSThreads=1
    networks:
      kitler:
        aliases:
          - elastic
volumes:
  esdata:
    driver: local

networks:
  kitler: